name: build_docker_image

on:
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-20.04

    steps:
      - name: ğŸ’€ Check Out Repository
        uses: actions/checkout@v3
      
      - name: ğŸ˜ƒ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yuanqichau
          password: ${{ secrets.DOCKER_HUB_PAT }}
      
      - name: ğŸ˜• Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: ğŸ§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸš€ Build and Push ROS Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: yuanqichau/robot_sim:${{ github.ref_name }}
          cache-from: type=registry,ref=yuanqichau/robot_sim:${{ github.ref_name }}-buildcache
          cache-to: type=registry,ref=yuanqichau/robot_sim:${{ github.ref_name }}-buildcache,mode=max
            